os: linux
language: generic
services:
 - xvfb
before_script:
 - export TZ=Europe/London
 - chmod +x .travis/before_script.sh
 - chmod +x .travis/test.sh
 - .travis/before_script.sh
script:
 - .travis/test.sh
