name: launchdarkly_flutter
description: This is an unofficial LaunchDarkly SDK for Flutter, for anyone willing to use LaunchDarkly in a Flutter app.
version: 0.4.0
homepage: https://github.com/andre-paraense/launchdarkly_flutter
issue_tracker: https://github.com/andre-paraense/launchdarkly_flutter/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.oakam.launchdarkly_flutter
    pluginClass: LaunchdarklyFlutterPlugin