name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
      - run: flutter pub publish --dry-run
      - uses: actions/slack-notifier-action@v1.0.2
        with:
          webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}