name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
      - run: cd $FLUTTER_HOME
      - run: mkdir -p .pub-cache
      - run: echo '{"accessToken":"${{secrets.accessToken}}", "refreshToken":"${{secrets.refreshToken}}, "tokenEndpoint":"https://accounts.google.com/o/oauth2/token", "scopes":["openid","https://www.googleapis.com/auth/userinfo.email"], "expiration":${{secrets.expiration}}}' > .pub-cache/credentials.json
      - run: cd $GITHUB_WORKSPACE
      - run: flutter pub publish -f