name: CI

on: [push, pull_request]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
      - run: flutter packages get
      - run: flutter analyze --no-pub
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
      - uses: actions/slack-notifier-action@v1
        with:
          webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
