name: CI

on: [push]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - run: flutter packages get
      - run: flutter analyze --no-pub
      - run: flutter test --coverage
      - run: flutter pub publish --dry-run
      - uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: CI - Build and Test
          JOB: ${{toJson(job)}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
